version: "3.9"
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=grange@astron.nl"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  dolfje:
    build: dolfje
    depends_on:
      dolfdb:
        condition: service_healthy
    environment:
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - MNOT_ADMIN_PASS=${MNOT_ADMIN_PASS}
      - APPLANG=${APPLANG}
      - REG_CHANNEL=${REG_CHANNEL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=${DB_DATABASE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dolfje.rule=Host(`${SLACK_URL}`)"
      - "traefik.http.routers.dolfje.entrypoints=websecure"
      - "traefik.http.routers.dolfje.tls.certresolver=myresolver"
    restart: unless-stopped
  dolfdb:
    build: dolfdb
    environment:
      - MYSQL_DATABASE=${DB_DATABASE} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS} 
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-u","pinger", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
